### ISSUE TITLE
在生成答案的时候切换会话或窗口，会话会重新渲染

### ISSUE THREAD

**Issue by CaiwenWang** [youngle316/power-chatgpt#18]

**Comment by ttpss930141011** [comment]
Hello @CaiwenWang & @youngle316 

這個問題只需要在 `src\components\PromptInput.tsx` 中 fetchEventSource 後的 config 加上 openWhenHidden: true 即可解決。

```
// src\components\PromptInput.tsx
...
    await fetchEventSource("/api/askQuestion", {
        signal: abortController?.signal,
        openWhenHidden: true,          /* here */
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          apiKey: apiKeyValue,
          apiBaseUrl: apiEndPointValue,
...
```

ref: [@microsoft/fetch-event-source](https://github.com/Azure/fetch-event-source/blob/a0529492576e094374602f24d5e64b3a271b4576/src/fetch.ts#L50C5-L50C5)

**Comment by youngle316** [comment]
@ttpss930141011 @CaiwenWang 谢谢，问题已经解决了 #26
