### ISSUE TITLE
好像不支持自定义API Proxy：ai.fakeopen.com

### ISSUE THREAD

**Issue by geekbb** [youngle316/power-chatgpt#28]
这里应该怎么填写？
https://ai.fakeopen.com/v1/chat/completions
https://ai.fakeopen.com/v1
<img width="514" alt="image" src="https://github.com/youngle316/power-chatgpt/assets/46196358/e69de200-9dfb-46d1-864e-1f042a588330">

**Comment by youngle316** [comment]
支持的，例如这个项目中的教程 https://github.com/x-dr/chatgptProxyAPI，使用 Cloudflare Worker 中转 api.openai.com

我有创建过一个 https://openaiproxy-4bc.pages.dev/v1，可以试着使用

**Comment by geekbb** [comment]
其实我是想使用https://github.com/pengzhile/pandora/issues/837
但这个项目只支持ai.fakeopen.com请求

**Comment by geekbb** [comment]
<img width="552" alt="CleanShot 2023-08-27 at 12 47 50@2x" src="https://github.com/youngle316/power-chatgpt/assets/46196358/f3773d3a-2aad-4ab3-b84b-df8fd80713df">
可以了，谢谢
